name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: self-hosted

    steps:
      - name: Pull latest backend
        run: |
          cd /opt/project/backend
          git pull origin main

      - name: Build backend
        run: |
          cd /opt/project/deployment
          docker compose up -d --build backend

      - name: Run migrations
        run: |
          cd /opt/project/deployment
          docker compose exec -T backend npx prisma migrate deploy

      - name: Cleanup Docker Images
        run: |
          docker image prune -f
          docker builder prune -f
